name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejs-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejs-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejs-app:latest

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejs-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejs-app:latest

      # OPTIONAL: Auto-update image tag in the GitOps repo with a commit/PR
      # You can automate K8s manifest update in the GitOps repo using "EndBug/add-and-commit" or a similar action
      # See below for an example step (requires repo write access set up)

      # - name: Update image tag in GitOps repo
      #   run: |
      #     # clone, modify k8s YAML, commit, push
      #   env:
      #     GITOPS_REPO: https://github.com/<your-org>/<gitops-repo>.git
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

